apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: gpu-swarm-trader
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:password@postgres:5432/gpuswarm"
  REDIS_URL: "redis://redis:6379"
  JWT_SECRET: "your-production-jwt-secret"
  JWT_REFRESH_SECRET: "your-production-refresh-secret"
  SENTRY_DSN: "https://your-sentry-dsn@sentry.io/project"
